---
- hosts: localhost
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  gather_facts: no

  tasks:
    - python_requirements_facts:
        dependencies:
          - openshift
          - requests

    - name: validate machine sets
      block:
      - debug:
          msg: Checking your current machinesets
      - name: get machinesets list    
        k8s_facts:
          api_version: machine.openshift.io/v1beta1
          kind: MachineSet
          namespace: openshift-machine-api
        register: r_get_machinesets
        until: r_get_machinesets | json_query('resources[?spec.template.metadata.labels.\"machine.openshift.io/cluster-api-machine-role\"==`workerocs`].status.readyReplicas') | count | int == 3
        retries: 20
        delay: 15
      - debug: 
          msg:
            - "You currently have {{ r_get_machinesets | json_query('resources[?spec.template.metadata.labels.\"machine.openshift.io/cluster-api-machine-role\"==`workerocs`].status.readyReplicas') | count }} ready OCS worker machinesets"


